git-credential-lib: encode Windows cred attributes as utf-8
The API expects attribute values to contain binary data, otherwise:
> TypeError: expected an object with a buffer interface