dist/pull: make more resilient against "broken" gitconfig
This time caused by:
  error: Malformed value for push.default: upstream
  error: Must be one of nothing, matching, tracking or current.
in 1.7.2.5... Oh well.